version: "2"
services:
  selenium-server:
    image: selenium/standalone-chrome:3.8.1-bohrium
    ports:
      - "4444:4444"
  scraper:
    image: brightredchilli/who_is_watching/scraper
    volumes:
      - /images:/images
    environment:
      - SELENIUM_HOST=http://selenium-server:4444/wd/hub
      - IMAGE_VOLUME=/images/
    depends_on:
      - selenium-server
